// Generated by dts-bundle v0.7.3

export class Button {
    constructor(action: string, onClick: (e: MouseEvent) => void);
    get(): HTMLButtonElement;
}

export class Canvas {
    constructor(width: string, height: string, lineWidth: number, color: string, imageName: string);
    get(): HTMLCanvasElement;
    setLineWidth(lineWidth: number): void;
    setColor(color: string): void;
    clear(): void;
    download(): void;
    undo(): void;
    redo(): void;
}

export class ColorPicker {
    constructor(color: string, onChange: (value: string) => void);
    get(): HTMLInputElement;
    setColor(color: string): void;
}

type PaintPadOptions = {
    width?: string;
    height?: string;
    lineWidth?: number;
    lineWidthMin?: number;
    lineWidthMax?: number;
    color?: string;
    imageName?: string;
    hasSlider?: boolean;
    hasColorPicker?: boolean;
    canClear?: boolean;
    canDownload?: boolean;
    canChangeState?: boolean;
};
export class PaintPad extends HTMLElement {
    constructor(opt?: PaintPadOptions);
    clear(): void;
    download(): void;
    undo(): void;
    redo(): void;
    setColor(color: string): void;
    setLineWidth(lineWidth: number): void;
    getDataURL(): string;
    getBlob(callback: BlobCallback, type?: string | undefined, quality?: number): void;
}
export {};

export class Slider {
    constructor(min: number, max: number, value: number, onChange: (value: number) => void);
    get(): HTMLInputElement;
    setValue(value: number): void;
}

